### ISSUE TITLE
Ability to change user password

### ISSUE THREAD

**Issue by muety** [muety/anchr#11]

**Comment by alexyiangou** [comment]
Hey there! I can handle this :slightly_smiling_face:

**Comment by n1try** [comment]
Sure, give it at try! :slightly_smiling_face:
Remember that you would need to change both frontend and backend. The latter is just a few lines of code. For the frontend, you would probably have to introduce a new kind of "settings" page, which can be accessed through a new _Settings_ button to the left of the _Logout_ button at the top right.
Other suggestions on where to place the password change in the UI are welcome, of course. :wink:

**Comment by alexyiangou** [comment]
I got 2 issues..
When trying to setup, I run ``source env.sh`` I get the error ``bash: export: `#': not a valid identifier``

Then when trying to continue installation, everything is successful, but I cant connect to the db and the app doesnt run..

Can I get some help here? :slightly_smiling_face:

**Comment by n1try** [comment]
Did you copy the `.env.example` to `.env` and add in your DB credentials etc.? If so, try to just remove the one exemplary comment in `.env`.

Concerning the database: do you know the exact reason why it can't connect? And can you give some details about your database? Did you set up a Mongo locally? Are you using Docker? Or a hosted online service? Can you connect to your database from the command-line with a GUI tool like [RoboMongo](https://robomongo.org/) ?

**Comment by alexyiangou** [comment]
Yeah man, I have followed the instructions on README, so I have copied the ``.env.example`` and set the default values on my ``.env``.

The error im getting for the db is this
```
Error: unable to connect to database 
  at NativeConnection.<anonymous> (/home/administrator/Documents/Alexandros/Projects/anchr/app.js:10:9)     
  at NativeConnection.emit (events.js:182:13)     
  at NativeConnection.Connection.error (/home/administrator/Documents/Alexandros/Projects/anchr/node_modules/mongoose/lib/connection.js:425:8)     
  at /home/administrator/Documents/Alexandros/Projects/anchr/node_modules/mongoose/lib/connection.js:452:14     
  at /home/administrator/Documents/Alexandros/Projects/anchr/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:58:21     
  at /home/administrator/Documents/Alexandros/Projects/anchr/node_modules/mongoose/node_modules/mongodb/lib/db.js:224:14     
  at Server.<anonymous> (/home/administrator/Documents/Alexandros/Projects/anchr/node_modules/mongoose/node_modules/mongodb/lib/server.js:234:9)     
  at Object.onceWrapper (events.js:273:13)     
  at Server.emit (events.js:182:13)     
  at Pool.<anonymous> (/home/administrator/Documents/Alexandros/Projects/anchr/node_modules/mongodb-core/lib/topologies/server.js:269:68)     
  at Object.onceWrapper (events.js:273:13)     
  at Pool.emit (events.js:182:13)     
  at Connection.<anonymous> (/home/administrator/Documents/Alexandros/Projects/anchr/node_modules/mongodb-core/lib/connection/pool.js:81:12)     
  at Object.onceWrapper (events.js:273:13)     
  at Connection.emit (events.js:182:13)     
  at Socket.<anonymous> (/home/administrator/Documents/Alexandros/Projects/anchr/node_modules/mongodb-core/lib/connection/connection.js:124:49)
```

**Comment by n1try** [comment]
Maybe try setting the env vars manually, instead of using the bash script, i.e. manually run `export ANCHR_DB_URL=...`, `export ANCHR_SECRET=...` and so on?

**Comment by alexyiangou** [comment]
Oh I also dont have mongodb installed locally. Im running on ubuntu machine. Do I need the mongodb cli tools before continuing exporting manually?

**Comment by n1try** [comment]
So, you don't necessarily need the mongo cli, unless you want to manually check the connection or something.
